libcufft.so.10: failed to map segment from shared object
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback): /usr/local/lib/python3.9/site-packages/nvidia/cufft/lib/libcufft.so.10: failed to map segment from shared object
Traceback:
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "/app/app.py", line 2, in <module>
    from transformers import pipeline
File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
File "/usr/local/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
File "/usr/local/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1101, in _get_module
    raise RuntimeError(